#!/usr/bin/env python3
# Copyright 2026 PJ Mullin. Licensed under the Apache License, Version 2.0.
"""Build the runtime public prompt module from the admitted review ledger."""

from __future__ import annotations

import hashlib
import json
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "verification" / "prompt_bank_human_review_v1.jsonl"
OUTPUT = ROOT / "environment_lab" / "accessbench_env" / "core_prompt_bank_v1.py"
SURFACES = (0, 1, 2, 4)


def literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    rows = [
        json.loads(line)
        for line in LEDGER.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if len(rows) != 600 or any(
        row["semantic_review_decision"] != "pass" for row in rows
    ):
        raise SystemExit("the review ledger does not contain 600 semantic review passes")
    by_blueprint = defaultdict(dict)
    for row in rows:
        by_blueprint[row["blueprint_id"]][int(row["surface"])] = row["prompt"]
    if len(by_blueprint) != 150:
        raise SystemExit(f"expected 150 workflows, found {len(by_blueprint)}")
    for blueprint_id, prompts in by_blueprint.items():
        if set(prompts) != set(SURFACES):
            raise SystemExit(f"{blueprint_id}: core prompt surfaces are incomplete")

    ledger_sha = hashlib.sha256(LEDGER.read_bytes()).hexdigest()
    lines = [
        "# Copyright 2026 PJ Mullin. Licensed under the Apache License, Version 2.0.",
        '"""Generated local development prompts for the AccessBench v1 core.',
        "",
        "Generated by verification/build_core_prompt_module.py from the admitted",
        "item-level semantic review ledger. Do not edit this module by hand.",
        '"""',
        "",
        f'PROMPT_REVIEW_LEDGER_SHA256 = "{ledger_sha}"',
        "CORE_PROMPT_SURFACES = (0, 1, 2, 4)",
        "CORE_PROMPTS_BY_BLUEPRINT = {",
    ]
    for blueprint_id in sorted(by_blueprint):
        lines.append(f"    {literal(blueprint_id)}: {{")
        for surface in SURFACES:
            lines.append(
                f"        {surface}: {literal(by_blueprint[blueprint_id][surface])},"
            )
        lines.append("    },")
    lines.extend([
        "}",
        "",
        "if len(CORE_PROMPTS_BY_BLUEPRINT) != 150:",
        '    raise ValueError("core prompt bank must contain 150 workflows")',
        "if any(set(prompts) != set(CORE_PROMPT_SURFACES) for prompts in CORE_PROMPTS_BY_BLUEPRINT.values()):",
        '    raise ValueError("core prompt bank surfaces are incomplete")',
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} with {len(rows)} prompts")


if __name__ == "__main__":
    main()
